### ISSUE TITLE
`hyper-snazzy.sh` breaks when there are no user profiles for the gnome-terminal yet

### ISSUE THREAD

**Issue by curusarn** [tobark/hyper-snazzy-gnome-terminal#3]
~I installed `gconf` but that did not solve the issue.~
~Is `gconftool` something I would have on my system?~
~I can't find any package with it for Manjaro.~
EDIT: This is what I get when I run `hyper-snazzy.sh` on a fresh machine:
```
❯ chmod +x hyper-snazzy.sh && ./hyper-snazzy.sh 
./hyper-snazzy.sh: line 104: gconftool: command not found
./hyper-snazzy.sh: line 104: gconftool: command not found
./hyper-snazzy.sh: line 88: gconftool: command not found
./hyper-snazzy.sh: line 88: gconftool: command not found
./hyper-snazzy.sh: line 88: gconftool: command not found
./hyper-snazzy.sh: line 88: gconftool: command not found
./hyper-snazzy.sh: line 88: gconftool: command not found
./hyper-snazzy.sh: line 88: gconftool: command not found
./hyper-snazzy.sh: line 88: gconftool: command not found
./hyper-snazzy.sh: line 88: gconftool: command not found
```

**Comment by curusarn** [comment]
Apparently, this condition fails and then the fallback for older Gnome fails as well resulting in "`gconftool` not found" errors.
```
❯ [[ -n "$(dconf list /org/gnome/terminal/legacy/profiles:/)" ]] && echo pass || echo fail
fail
```

**Comment by curusarn** [comment]
There is no dir for terminal in the settings:
```
❯ dconf list /org/gnome/         
control-center/
desktop/
evolution-data-server/
mutter/
nautilus/
settings-daemon/
shell/
```
So this command returns nothing:
```
❯ dconf list /org/gnome/terminal/legacy/profiles:/

```

**Comment by curusarn** [comment]
After I create a new profile for the gnome-terminal using the GUI:
```
❯ dconf list /org/gnome/terminal/legacy/profiles:/
:169458fc-9172-48fb-b2a4-d030c18fb43b/
list
```

So the issue is that `hyper-snazzy.sh` breaks when there are no user profiles for the gnome-terminal yet

**Comment by curusarn** [comment]
Did you get the script for adding gnome-terminal profiles from some other project?
Should I report the issue upstream?

**Comment by yihyunjoon** [comment]
@curusarn I'm sorry for your inconvenience. Yes, actually it doesn't create new terminal profile, but it replaces the existing terminal profile. 

I made this script with [terminal.sexy](https://terminal.sexy/). Check this [repo](https://github.com/stayradiated/terminal.sexy) please.

Thank you.

**Comment by curusarn** [comment]
The weird thing is that the previous profile is still available. What exactly does "replaces the existing terminal profile" mean?

**Comment by curusarn** [comment]
I have just raised an issue in the terminal.sexy repo: https://github.com/stayradiated/terminal.sexy/issues/61
